// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nyhmaazhsmdjjensaczc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im55aG1hYXpoc21kamplbnNhY3pjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyMjQ5OTcsImV4cCI6MjA2OTgwMDk5N30.cyOeGbuSeKk-OCecWl161QoIYgFUsQxRV64UJgvXB6U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});